"""
One-way streaming channel over a dedicated pipe.

A `StreamChannel` opens its own pipe (separate from the control pipe),
waits for a client to subscribe, and then exposes `emit(event, data)` as
the sole writer-side API. The client consumes length-prefixed MessagePack
frames from the pipe until it sees a `"done"` or `"error"` event.

## Why a separate pipe per stream
- Stream data (audio PCM, chunks, etc.) can be large and slow to consume.
  Keeping it off the control pipe means one long-running job never blocks
  unrelated request/response traffic.
- Cancellation is trivial: when the client closes the stream pipe, the
  underlying `StreamWriter` sees the loss and the channel's emit loop
  raises `ConnectionResetError`. The module catches that and tears down
  its work.

## Capacity / backpressure
Each channel has a bounded internal `asyncio.Queue`. `emit()` puts the
event onto that queue; a background writer task drains the queue into
the pipe. When the queue is full, `emit()` awaits a slot — that's the
backpressure the producer (the model) feels, independent of whatever the
OS pipe buffer size happens to be.

Set `capacity` on channel creation based on the producer's memory profile:
large audio models with VRAM pressure should pick small capacities (≈ 3-5),
cheap producers can be generous (≈ 32-100).

## Lifecycle

    channel = await StreamChannel.open(transport, capacity=10)
    # Expose channel.id + channel.endpoint.address to the caller via the
    # control-pipe response, so the client knows where to connect.

    try:
        await channel.wait_for_client(timeout=10.0)
        async for chunk in producer():
            await channel.emit("chunk", {...})
        await channel.emit("done", {...})
    finally:
        await channel.close()

The same channel is used across its whole life; you don't reopen or reuse.
"""

from __future__ import annotations

import asyncio
import logging
import uuid
from typing import Any

from ipc import framing
from ipc.transport import Endpoint, Reader, Transport, Writer


_log = logging.getLogger(__name__)


#: Default capacity when none is specified. Enough for most streamers to
#: absorb small jitter, small enough that a stalled consumer can't balloon
#: memory.
DEFAULT_CAPACITY = 32


class StreamChannel:
    """
    A single unidirectional stream from the daemon to one client.

    Opens its own pipe via the given `Transport`, waits for a client to
    subscribe, then forwards `emit()`-ed events as length-prefixed
    MessagePack frames until `close()`.

    ## Attributes
    - `id` — Short unique identifier for this stream. Passed back to the
      client over the control pipe so it knows which job is which.
    - `endpoint` — The `Endpoint` describing the pipe address. Pass
      `endpoint.address` to the client.
    """

    def __init__(
        self,
        channel_id: str,
        endpoint: Endpoint,
        *,
        capacity: int,
    ) -> None:
        self._id = channel_id
        self._endpoint = endpoint
        self._capacity = capacity

        # Populated when a client connects.
        self._reader: Reader | None = None
        self._writer: Writer | None = None
        self._client_connected = asyncio.Event()

        # Producer → writer bridge. Sentinel `None` signals "drain and exit".
        self._out_queue: asyncio.Queue[tuple[str, Any] | None] = asyncio.Queue(
            maxsize=capacity
        )

        self._writer_task: asyncio.Task | None = None
        self._closed = False
        self._close_lock = asyncio.Lock()

        # Server-side handle for the listener (returned by Transport.listen).
        # Kept so close() can stop accepting new connections.
        self._server_close_cb = None

    # ── Factory ───────────────────────────────────────────────────────────────

    @classmethod
    async def open(
        cls,
        transport: Transport,
        *,
        capacity: int = DEFAULT_CAPACITY,
        name: str | None = None,
    ) -> "StreamChannel":
        """
        Create a new stream channel on its own pipe.

        ## Parameters
        - `transport` — The daemon's active `Transport`.
        - `capacity` — Max events buffered between producer and pipe.
          Once full, further `emit()` calls block (backpressure).
        - `name` — Optional channel id. Autogenerated (8-hex) if omitted.

        ## Returns
        The live `StreamChannel` — ready to be advertised to the client.
        A background writer task is already running, so the first
        `emit()` right after `wait_for_client()` works without setup.
        """
        channel_id = name or f"job_{uuid.uuid4().hex[:8]}"

        # Placeholder — filled in once transport.listen gives us an endpoint.
        channel = cls.__new__(cls)
        channel.__init__(channel_id, Endpoint(kind="", address=""), capacity=capacity)

        # A handler that just binds our reader/writer when a client shows up.
        async def handler(reader: Reader, writer: Writer) -> None:
            if channel._client_connected.is_set():
                # Someone already subscribed; refuse a second one.
                _log.warning(
                    "channel %s: second client attempted to subscribe, refusing",
                    channel_id,
                )
                try:
                    writer.close()
                    await writer.wait_closed()
                except Exception:
                    pass
                return

            channel._reader = reader
            channel._writer = writer
            channel._client_connected.set()

            # Keep the handler task alive until the writer task is done,
            # otherwise the connection would be torn down immediately.
            if channel._writer_task is not None:
                try:
                    await channel._writer_task
                except Exception:
                    # Already logged inside _run_writer.
                    pass

        endpoint = await transport.listen(channel_id, handler)
        channel._endpoint = endpoint

        # Start the writer now; it'll block until a client connects.
        channel._writer_task = asyncio.create_task(
            channel._run_writer(), name=f"stream-writer-{channel_id}"
        )

        _log.info("StreamChannel %s open at %s", channel_id, endpoint.address)
        return channel

    # ── Public API ────────────────────────────────────────────────────────────

    @property
    def id(self) -> str:
        return self._id

    @property
    def endpoint(self) -> Endpoint:
        return self._endpoint

    @property
    def is_closed(self) -> bool:
        return self._closed

    @property
    def has_client(self) -> bool:
        return self._client_connected.is_set()

    async def wait_for_client(self, timeout: float | None = None) -> None:
        """
        Block until a client subscribes to this channel.

        ## Parameters
        - `timeout` — Max seconds to wait. `None` = wait indefinitely.

        ## Raises
        - `asyncio.TimeoutError` — No client connected within `timeout`.
        - `RuntimeError` — Channel was closed before a client connected.
        """
        if self._closed:
            raise RuntimeError("channel is closed")

        if timeout is None:
            await self._client_connected.wait()
        else:
            await asyncio.wait_for(self._client_connected.wait(), timeout)

    async def emit(self, event: str, data: dict | None = None) -> None:
        """
        Queue one event for the client.

        Blocks if the internal buffer is full (backpressure). Once
        `close()` has been called, further `emit()`s raise `RuntimeError`.

        ## Parameters
        - `event` — Short label, e.g. `"chunk"`, `"done"`, `"error"`.
        - `data` — Optional payload dict.

        ## Raises
        - `RuntimeError` — Channel already closed.
        """
        if self._closed:
            raise RuntimeError(f"channel {self._id} is closed")
        await self._out_queue.put((event, data or {}))

    async def close(self) -> None:
        """
        Gracefully tear down the channel.

        - Drains any queued events (they'll be emitted before shutdown).
        - Closes the pipe.
        - Stops the listener so no further clients can subscribe.

        Idempotent.
        """
        async with self._close_lock:
            if self._closed:
                return
            self._closed = True

        # Signal the writer task to drain and stop.
        await self._out_queue.put(None)

        if self._writer_task is not None:
            try:
                await self._writer_task
            except Exception:
                _log.exception("stream writer task raised during close")

        # Writer already closed the StreamWriter; nothing more to do for it.

    # ── Internal writer loop ──────────────────────────────────────────────────

    async def _run_writer(self) -> None:
        """
        Drain the outbox into the pipe.

        Waits for a client (populated by the `handler` in `open()`), then
        pulls events off `_out_queue` and writes framed messages. Exits
        when it sees the `None` sentinel (from `close()`) or when the
        peer disconnects (`ConnectionResetError`).
        """
        await self._client_connected.wait()

        if self._writer is None:
            # Client connected then vanished before we got the writer.
            return

        try:
            while True:
                item = await self._out_queue.get()
                if item is None:
                    break  # close() signalled end-of-stream

                event, data = item
                frame = {"type": event, "data": data}

                try:
                    await framing.write_frame_async(self._writer, frame)
                except (ConnectionError, OSError, BrokenPipeError) as e:
                    _log.info(
                        "stream %s: client disconnected (%s); stopping writer",
                        self._id, e,
                    )
                    self._closed = True
                    break

        except asyncio.CancelledError:
            raise
        except Exception:
            _log.exception("stream %s: writer loop crashed", self._id)
        finally:
            # Best-effort writer close.
            try:
                if self._writer is not None:
                    self._writer.close()
                    await self._writer.wait_closed()
            except Exception:
                pass
